### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película por id (existe)
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar una película por id (no existe)
GET http://localhost:3000/movies/2

### Recuperar todas las películas por un género
GET http://localhost:3000/movies?genre=Drama

### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1972,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime", "Drama"
    ],
    "rate": 9.2
 }

### Editar datos sobre una película
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1901
}

### Eliminar una película
DELETE http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3