[functions]
    directory = "functions"
    external_node_modules = ["express"]
    node_bundler = "esbuild"
[[redirects]]
    force = true
    from = "/*"
    to = "/.netlify/functions/index/:splat"
    status = 200